import type { Metadata } from "next";
import { Familjen_Grotesk } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const familjen_grotesk = Familjen_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "3otol",
  description: "Generated by next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={familjen_grotesk.className}>
        <Navbar />
        <main className="w-full min-h-screen">
          {children}
        </main>
      </body>
    </html>
  );
}
